# Generated by Django 5.0.4 on 2024-04-28 09:34

from django.db import migrations, connection


course_insert_trigger = "course/sql/insert_trigger.sql"
drop_trigger = "DROP FUNCTION IF EXISTS course_before_insert_update_trigger"


def create_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(open(course_insert_trigger).read())


def remove_trigger(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(drop_trigger)


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_trigger, remove_trigger),
    ]
